services:
  - type: web
    name: gpt5-responses-api
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python flask_gpt5_integration_final.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: AI_MODEL
        value: gpt-5
      - key: AI_COMPLETIONS_MODEL
        value: gpt-5-chat-latest
      - key: AI_MODEL_FALLBACK
        value: gpt-4o
      - key: MAX_OUTPUT_TOKENS
        value: 800
      - key: TIMEOUT_S
        value: 60
      - key: FALLBACK_CHAT
        value: 1
    healthCheckPath: /api/gpt5/health